name: Create a release

env:
  BRANCH: ${{ github.ref_name }}
  VERSION: 0.0.0.7

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Check build condition for Snap
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.9'
          - '3.10'
    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0
      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64
      - id: code-checks
        name: Make sure the code follows conventions and tests correctly
        run: |
          make checks
      - id: build-package
        name: Build package
        run: |
          poetry build
      - name: Add version to environment vars
        run: |
          echo "PROJECT_VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
      - name: Check if tag version matches project version
        run: |
          TAG=$(git describe HEAD --tags --abbrev=0)
          echo $TAG
          echo $PROJECT_VERSION
          if [[ "$TAG" != "v$PROJECT_VERSION" ]]; then exit 1; fi
      - name: Release Notes
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.SPARK_PKG_PUBLISH }}
          output: ".github/RELEASE-TEMPLATE.md"
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SPARK_PKG_PUBLISH }}
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          files: |
            spark_client-${{env.PROJECT_VERSION}}-py3-none-any.whl
            spark_client-${{env.PROJECT_VERSION}}.tar.gz

  test:
    name: Test Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download tar.gz file
        run: |
          mkdir pkgs
          # curl download the release and test ?
          rm -rf pkgs
